name: Check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check-packages:
    name: Check Packages
    runs-on: ubuntu-24.04
    steps:
      - name: Check Out
        uses: actions/checkout@v4.2.2

      - name: Check Dependencies
        run: |
          go mod tidy
          git diff --exit-code HEAD

      - name: Check Formatting
        run: |
          go fmt ./...
          git diff --exit-code HEAD
