name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check-packages:
    name: Check Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Check Formatting
        run: |
          go fmt ./...
          git diff --exit-code HEAD

  test-packages:
    name: Test Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Run Tests
        run: go test -v ./...
