name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test-packages:
    name: Test Packages
    runs-on: ubuntu-24.04
    steps:
      - name: Check Out
        uses: actions/checkout@v4.2.2

      - name: Set Up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version-file: go.mod

      - name: Run Tests
        run: go test -v ./... -coverprofile=.cover.out -covermode=atomic -coverpkg=./...

      - name: Check Coverage
        uses: vladopajic/go-test-coverage@v2.10.5
        with:
          profile: .cover.out
          threshold-file: 100
          threshold-package: 100
          threshold-total: 100
